### ISSUE TITLE
[Other] Poprawka edycyjna

### ISSUE THREAD

**Issue by dkarczewski** [SteelPh0enix/stm32materials#1]
Drobne poprawki edycyjne.

* W punkcie 4 przy listingu, brakuje typu zmiennej.
```c
/* USER CODE BEGIN PV */
unsigned uint32_t buttonCounter = 0;
/* USER CODE END PV *
```
* W punkcie 5.5:
  * podczas numerowania: `Odbiór`,
  * w nagłówku funkcji `bool erase_application(...)` brakuje typu argumentów tj. `uint32_t`,
  * w nagłówku funkcji `bool flash_and_verify(...)` do przeniesienia deklaracja stałego wskaźnika tj. `bool flash_and_verify(const uint8_t* const bytes, size_t const amount, uint32_t const offset) {...}`

**Comment by SteelPh0enix** [comment]
>W punkcie 4 przy listingu, brakuje typu zmiennej.

nie, nie brakuje :). `unsigned` to pełnoprawny typ (skrócona nazwa na `unsigned int`): https://en.cppreference.com/w/c/language/arithmetic_types

>podczas numerowania: `Odbiór`,

Dzięki, poprawione

>w nagłówku funkcji `bool erase_application(...)` brakuje typu argumentów tj. `uint32_t`,

Nie, nie brakuje, patrz wyżej

>w nagłówku funkcji `bool flash_and_verify(...)` do przeniesienia deklaracja stałego wskaźnika tj. `bool flash_and_verify(const uint8_t* const bytes, size_t const amount, uint32_t const offset) {...}`

to konwencja *east const* która moim zdaniem jest trochę bardziej przejrzysta od *west const*, a działa tak samo. Nie ma znaczenia po której stronie umieścisz `const`, ważna jest kolejność. Więcej na ten temat można przeczytać tutaj: https://mariusbancila.ro/blog/2018/11/23/join-the-east-const-revolution/
Oraz obejrzeć tutaj: https://www.youtube.com/watch?v=fv--IKZFVO8

**Comment by dkarczewski** [comment]
> nie, nie brakuje :). unsigned to pełnoprawny typ (skrócona nazwa na unsigned int): https://en.cppreference.com/w/c/language/arithmetic_types

Racja :)

Odnośnie konwencji _east const_ i _west const_, dzięki za wskazanie artykułów :)
